name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Compose
        run: |
          docker compose version
          docker compose up -d postgres
          sleep 10

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Test
        run: make test
